FROM php:8.1.25-fpm
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

RUN docker-php-ext-install pdo pdo_mysql mysqli mbstring exif pcntl bcmath gd
RUN docker-php-ext-enable pdo_mysql